### ISSUE TITLE
Migrate to Swift 2.0

### ISSUE THREAD

**Issue by xwv** [XWebView/XWebView#10]
Source written in Swift 1.2 can't compiled with Xcode 9 beta 5. Swift 2.0 has both many feature improvements and bug fixes.

**Comment by andriyslyusar** [comment]
Hi David, would you push swift 2 compatible version to cocoapods?

**Comment by xwv** [comment]
Yes, I will submit a PR for that when it ready. Currently, most porting works are done, you can fetch the code from https://github.com/xwv/XWebView/tree/swift2
I'm trying to find a way to handle loadFileURL well both on iOS8 and 9.

**Comment by xwv** [comment]
Just merged.
@andreyslyusar, are you using XWebView or plan to use it?
If you're using it, could you please confirm it works for you?

**Comment by xwv** [comment]
Version 0.9.4 is published on CocoaPods.
Close
