### ISSUE TITLE
Problem with code

### ISSUE THREAD

**Issue by ghost** [XWebView/XWebView#18]
Im a newbie in IOS... I trying to do the Quick Start guide, but unfortunelly, Xcode throws about 30 compilation errors.... I use Product -> Analyze option.... So I set target 8 and use Xcode 7 beta.

Some errors are with the # ... I dont understand any more...

Please help me

**Comment by fernandodev** [comment]
May you post log error and the version you are using?

**Comment by ghost** [comment]
Fernando, you speak spanish?

**Comment by fernandodev** [comment]
You can try even though I speak Portuguese ;)
But in general words prefer English to help others with the same doubt.

**Comment by ghost** [comment]
I have an error that says: WKWebView does not have a amember name loadPlugin

**Comment by fernandodev** [comment]
You must link XWebView.framework in your XCodeProject and import it.

**Comment by ghost** [comment]
OK, I allready added in the section "Linked frameworks and libraries" and add import XWebView in ViewCOntroller.swift but import is broken.... not a module says...

**Comment by fernandodev** [comment]
Can it be [that](http://stackoverflow.com/questions/29500227/xcode-no-such-module-error-but-the-framework-is-there)?

**Comment by ghost** [comment]
![screen shot 2015-10-01 at 11 11 23 am](https://cloud.githubusercontent.com/assets/263420/10223060/951f542a-682d-11e5-9820-418219d8de57.png)
![screen shot 2015-10-01 at 11 11 47 am](https://cloud.githubusercontent.com/assets/263420/10223061/955010e2-682d-11e5-9ed7-38cf8bd904c1.png)

I downloaded the sample proyect and opened in Xcode... the are the compilation errors...

**Comment by fernandodev** [comment]
I suppose that sample project from https://github.com/XWebView/Sample is not updated yet. I'm working on a new branch to improve new fixes for iOS 9.x/8.x and there is a new Sample under construction

**Comment by ghost** [comment]
So, what is the correct version of Xcode and swift to run the sample?

**Comment by fernandodev** [comment]
For a while swift 1.2 XCode 6.3
Take a look on this [branch](https://github.com/XWebView/XWebView/tree/fix-socket-timeout)

**Comment by xwv** [comment]
The sample project was updated for Swift 2.0 several days ago, check the latest commit.

**Comment by nathankeeney** [comment]
Hey all, I inherited an XCode project that utilizes XWV. When I updated to XCode 7 (not beta), I'm now getting several compilation errors similar to the ones in the screenshot above, from XWebView. I tried updating the pod (0.9.2 -> 0.9.3) and saw no improvement even after cleaning.

Also, when I restart XCode, I got the Swift Syntax Updater wizard. I allowed this to complete and now I actually have more compile errors (all in XWV) than before.

Is there an ETA for a version of XWV that is compatible with XCode 7? Something else I can do to fix these in the meantime? Thanks!

**Comment by xwv** [comment]
@nathankeeney , the master branch has Xcode 7 support, but it has not been published on cocoapods yet.

**Comment by nathankeeney** [comment]
@xwv Great! Any ETA for cocoapods version?

**Comment by xwv** [comment]
@nathankeeney, in 1 week since I'm outing. You can have a try for the last revision if convenient. So we may fix problems if any before publish to cocoa pods.

@fernandodev , I would like to include your changes about the readme and example (I like it :-) into the upcoming beta release. Can you make a PR for that?

**Comment by fernandodev** [comment]
@xwv For sure! I'm sorry for late because I've got super busy few days ago. But tomorrow I'll work on it again and split PR into small others.

**Comment by xwv** [comment]
@nathankeeney , version 0.9.4 was pushed to cocoapods.
Close
