### ISSUE TITLE
Objects as callback/promise result

### ISSUE THREAD

**Issue by ZeroZeroOne-dev** [XWebView/XWebView#37]
Is it possible to return an object as a result of a plugin function call? 

``` Swift
class Result{
    var a: String = "A";
}

class Plugin: NSObject, XWVScripting{
    func testFunc(promiseObject promiseObject: XWVScriptObject){
        promiseObject.callMethod("resolve", withArguments: [Result()]);
    }
}
```

**Comment by xwv** [comment]
This is a good question.
You can return an object as a plugin by reference, this means the JS object returned is connected to the native object:

```
class Result{
    dynamic var a: String = "A";
}

class Plugin: NSObject, XWVScripting{
    func testFunc(promiseObject promiseObject: XWVScriptObject){
        // The object has to be loaded as a plugin.
        // TODO: this should be done automatically, and should not pollute global namespace.
        let object = webview.loadPlugin(Result(), "window.someWhere");
        promiseObject.callMethod("resolve", withArguments: [object]);
    }
}
```

Currently, return by value is not supported. This is an item in my todo list. A proposal is:

```
class Result: XWVJSONRepresentable {
    var a: String = "A";
    var jsonString: String {
        return "{a: '\(a)'}"
    }
}

class Plugin: NSObject, XWVScripting{
    func testFunc(promiseObject promiseObject: XWVScriptObject){
        promiseObject.callMethod("resolve", withArguments: [Result()]);
    }
}
```

**Comment by ZeroZeroOne-dev** [comment]
Yeah im currently injecting the object as json as an alternative since i don't need to call any functions in the object, but by reference might be a better option, thanks :)

**Comment by xwv** [comment]
Finally, passing by value is supported.
struct, class and even enum types can be automatically converted to JSON with reflection.
Mean while, types which conform CustomJSONStringable (or ObjCJSONStringable for Objective-C) can provide their own JSON representation.
