### ISSUE TITLE
Swift 2.2 and NSInvocation

### ISSUE THREAD

**Issue by jameshartt** [XWebView/XWebView#39]
Hi there, love XWebView, it helped massively in transitioning a very popular app away from UIWebViews to WKWebViews and bring it all the benefits that has. I currently have a fork with some very messy changes that I hope to tidy up and maybe offer as a PR that helped resolve some issues I was having with relative paths in local HTML and Javascript.

Anyway, onto the issue, whilst checking dependancies for an app I'm currently work on, found that compiling under Swift 2.2 with Xcode 7.3 Beta 5, there is an issue with XWVInvocation's use of NSInvocation/MethodSignature.

<img width="987" alt="screen shot 2016-03-19 at 12 00 10" src="https://cloud.githubusercontent.com/assets/752200/13898482/308c968a-edca-11e5-909f-5468228870e9.png">

Any idea on how to proceed here? The extreme is obviously dropping down into Obj-C, but that would be a step backwards. Any ideas?

**Comment by xwv** [comment]
I'm not aware of this issue because I'm still using Xcode 7.0. Thanks, PRs are always welcome :-)
I'll try the latest version of Xcode when I have time(hopefully soon). The XWVInvocation uses a trick to workaround the restriction of NSInvocation in Swift. If it's blocked by Apple, we have to find another or back to OC.
Does the next line (_NSInvocation.invocationWithMethodSignature) work? There is no error in the screenshot. According to the error message, the next line should have the same problem.

**Comment by jameshartt** [comment]
Thank you for your response :smile:. Yeah, it did look like a trick that unfortunately doesn't work anymore. On first look at docs and generated Swift headers I couldn't really see another way around other than writing some Obj-C. We are soon planning to use the Scripting stuff (the main reason why I chose XWebView) for a Single Web View implementation of the app I'm working on. This should be within the next quarter (3 months), so I'm sure I can apportion some time to it in the near future. It would be good to co-ordinate so that we're not duplicating effort :-)

It's the same deal with _NSInvocation, yes, the method simply just doesn't exist on AnyObject or is in _any_ generated Swift header, just that the classes themselves are not possible.

Is there a different way to architect the native scripting? I worry that another trick could be wasted effort with the direction of Swift.

**Comment by xwv** [comment]
I tried to install CommandLine tools of Xcode 7.3beta5, but failed because I'm using Yosemite :-(
Here is my [1st try](https://gist.github.com/xwv/e472dac2a6a421a64fe0#file-trick-swift) for the issue. Does it work in Swift 2.2?

**Comment by jameshartt** [comment]
That try looks very reasonable and I'll give it a bash tomorrow on the train into work and raise a PR if successful. The only thing that concerns me is that Selector("...") is replaced in Swift with a type safe version. But really won't know until I try.

Thanks a lot for the steer :-)

**Comment by xwv** [comment]
Thanks for trying.
My [2nd try](https://gist.github.com/xwv/26ba4599632e27f76a3e#file-inv-swift)
This looks better than the 1st. I bet this will work :smile:

**Comment by jameshartt** [comment]
Cool, again, will try tomorrow and PR if successful :-)

**Comment by robin7331** [comment]
Is there any update on this? I have a urgend bugfix somewhere else and I am not able to proceed with building my project.

Is downgrading xcode the only way?

**Comment by xwv** [comment]
@robin7331 , there is an PR #41 contributed by @Cloudage. You can try to apply the patch for temporary workaround, it looks good though I have not tried. I need several days at least to work out final fix.

**Comment by jameshartt** [comment]
Yeah, I've just tried your second suggestion @xwv, but just need the extra time to do attempt the same with the method signature. May be until the weekend.

I do think when it comes down to it, PR #41 is the better approach.

There are still multitude of warnings with your approach and with Swift 3, the unsafe stringy `Selector("method")` approach will no longer work.

**Comment by jameshartt** [comment]
Using the suggestions of which to change the `Selector("...")` to `#selector(NSInvocation.method)`, result in compiler errors, for the obvious reasons, Apple _reallllly_ don't want you to use NSInvocation and NSMethodSignature in Swift.

**Comment by jameshartt** [comment]
Anyway, thanks for your steer and will have another hack at the weekend :-)

**Comment by robin7331** [comment]
Well thanks guys but I am not able to build my app..
I changed my Podfile to: `pod 'XWebView', :git => 'https://github.com/Cloudage/XWebView.git'` why is that not working?

f.ex.
`use of unresolved identifier 'FixSwift22'`

**Comment by jameshartt** [comment]
Dude, who cares about your app but you...? :stuck_out_tongue: 

It's probably because the Podspec file doesn't have any reference to the new Objective-C files, the person who made fork, likely doesn't use Cocoapods and uses something like Carthage. You could fork their repo and add the extra source and header files. The Podspec has enough comments to help you out, or go to the Cocoapods website and read some of the docs.

**Comment by robin7331** [comment]
Jeah dude, thanks.

Here's the thing. It is interesting to me how to generally use a forked repo that has fixed something instead of the main repo. Sometimes I'd like to do some changes on my own and use my fork. 
Did not know how to do that till now.

So thanks and cheers!

**Comment by xwv** [comment]
@jameshartt , please forget my last try. Yesterday, I spent 4 hours to upgrade my mac to 10.11 and Xcode to 7.3. Today I spent another 4 hours to found a perfect workaround without hacking.  I will submit an PR soon.

**Comment by jameshartt** [comment]
Amazing, I'm looking forward to seeing the result!

**Comment by xwv** [comment]
@jameshartt , please take a look at #42 .

**Comment by xwv** [comment]
Fixed.

**Comment by samingle** [comment]
Is this going to be bundled into a pod release? The version in Cocoapods is still non-functional for Swift 2.2.

**Comment by xwv** [comment]
Indeed, I'll publish a new version on Cocoapods.
