### ISSUE TITLE
Update cocoapods repository to support Swift 2.2

### ISSUE THREAD

**Issue by PixelsCommander** [XWebView/XWebView#44]
Could you please update cocoapods version to be 2.2 compatible? Thanks

**Comment by samingle** [comment]
+1

**Comment by xwv** [comment]
Yes, I'll update it soon.

**Comment by xwv** [comment]
[The new version 0.9.5 was just published on Cocoapods](https://cocoapods.org/pods/XWebView).
It seems that Cocoapods is approaching 1.0 release. I have not tested against the beta release. Please report bugs if any, thanks.
