### ISSUE TITLE
Remove iOS 8.x support

### ISSUE THREAD

**Issue by xwv** [XWebView/XWebView#45]
I plan to remove the code for iOS 8.x support in the near future. If you have concerns, please raise here.

FYI: The iOS 8.x [version statistics](https://developer.apple.com/support/app-store/) and [trend(nonofficial)](https://mixpanel.com/trends/#report/ios_8/from_date:-29,report_unit:day,to_date:1).

**Comment by nfarina** [comment]
Are there significant advantages to dropping iOS 8.x support?

Our team generally targets the last major version behind the current release version. So we wouldn't be able to drop iOS 8 until after iOS 10 is officially released.

**Comment by xwv** [comment]
Your concern does make sense. Thanks for the feedback.
Actually no significant advantages, just remove some hacking code.

**Comment by xwv** [comment]
iOS 8.x support was removed in Swift 3.0 migration, because the market share of iOS 8 is very low now. This legacy code is still available on swift-2.3 branch.
