### ISSUE TITLE
Return from methods

### ISSUE THREAD

**Issue by almaz1213** [XWebView/XWebView#52]
Hi,

I included XWebView into my code and it works: 
WebView!.loadPlugin(jsObj(), namespace: "injectedObj")

In the injected object I have a method:
@objc func getPlatform() -> String{
        print("   PLARFORNN")
        return "{\"code\":1}"
    }
it works and prints on the iOS emulator console. 

But it returns undefined in javascript code:
window.injectedObj.getPlatform();  // = undefined

could you give me a clue how can I get result from the method in javascipt in WebView?

Thanx

**Comment by xwv** [comment]
Native method can't pass the result to JavaScript by return value, because the communication between native and javascript is asynchronous. You have to pass the result back to JavaScript by callback.
Plugin:

```
@objc func getPlatform(callback: XWVScriptObject) {
    print(" PLARFORNN")
    callback.call(arguments: ["{\"code\":1}"], completionHandler: nil) 
}
```

JavaScript:

```
window.injectedObj.getPlatform(function(result){ /*your code */});
```

**Comment by almaz1213** [comment]
nice. works. thanx
