### ISSUE TITLE
use loadPlugin:namespace: VC cannot dealloc

### ISSUE THREAD

**Issue by semnyqu** [XWebView/XWebView#56]
@property (nonatomic, strong, readwrite) WKWebView *webView;
- (void)viewDidLoad {
  [super viewDidLoad];
  // Do any additional setup after loading the view.
  //webview
  _webView = [[WKWebView alloc] initWithFrame:self.view.bounds configuration:[WKWebViewConfiguration new]];
  _webView.navigationDelegate = self;
  [self.view addSubview:_webView];
  
  ```
  [_webView loadPlugin:js namespace:@"test"];
  ```
  
  }

use this  [_webView loadPlugin:js namespace:@"test"];
cannot release vc

**Comment by semnyqu** [comment]
[_webView loadPlugin:js namespace:@"test"];
is a big bug

**Comment by xwv** [comment]
Sorry, I don't quite understand the problem you report. I suppose the 'VC' means ViewController, but XWebView doesn't touch any ViewController instance.  So what do you mean about "cannot release vc"? What is your expectation?
