### ISSUE TITLE
Possibility to plugin return values synchronized

### ISSUE THREAD

**Issue by ghost** [XWebView/XWebView#63]
Hi!
I would like to ask whats changes and fixes are neccesary to allow this plugin can return values synchronized and without any callback or promise.

The reason for this is I have a centralized angularJS App that owner not allow me to access to source to modify it.

Thanks a lot!!!

**Comment by soflare** [comment]
It's possible, but very very tricky. And it's also dangerous to make your app unresponsive.

**Comment by mihey8800** [comment]
@mraffo have you solved this?
