### ISSUE TITLE
Swift 3 version not available on CocoaPods

### ISSUE THREAD

**Issue by shadone** [XWebView/XWebView#65]
Hi there,

Thanks for making XWebView, I started using it recently and it is pretty awesome.

That being said I am in the process of moving our app to Swift 3 and noticed that despite what the [https://github.com/XWebView/XWebView#xwebview-vs-swift](docs say) the Swift 3 version of XWebView is not available through cocoapods. The latest version that I see is 0.10.0 - see https://cocoapods.org/?q=xwebview

What's the status of Swift 3 support and whether the are near future plans to release it?

**Comment by xwv** [comment]
Thanks for your support.
The swift 3 support is considering in beta stage, and I have 2 coming fixes/improvements. Hopefully I can finish them in 2 weeks because I'm quite busy recently.
You can temporarily import the project through git submodule for testing.

**Comment by xwv** [comment]
I pushed the 0.12.0 version to Cocopods. It supports Swift 3.0.
