### ISSUE TITLE
Upon reloading a plugin, userScripts are disabled.

### ISSUE THREAD

**Issue by shirakaba** [XWebView/XWebView#73]
On first startup, I'd like to load a plugin into my webView:

- `webView.loadPlugin(Tokenising("zh-Hans"), namespace: "Tokenising")`

Later, when an action button is pressed in the toolbar, I'd like to re-initialise the plugin and load it in again to the same namespace:

- `webView.loadPlugin(Tokenising("ja"), namespace: "Tokenising")`

A user script is added, which should call a function from the current instance of the Tokenising class: 
 ```
let userScript = WKUserScript(
    source: /* All the contents of userScript.js, which will declare and run `exampleFunction()`, which calls `window.Tokenising.romaniseobj()` */,
    injectionTime: WKUserScriptInjectionTime.atDocumentEnd,
    forMainFrameOnly: false
)
```

The user script runs its `exampleFunction()` function perfectly – which, for this example, simply makes the whole background of the page green – until I reload the plugin. Upon reloading the plugin, the Tokenising class _does_ still remain available in JavaScript, however, the user script is deleted (i.e.. `window.exampleFunction` cannot be found).

Nonetheless, Swift reports that a memory address for the user script is still attached to `webView.configuration.userContentController`, so it's clearly floating around somewhere. Even if I manually remove the user script and re-add it, JavaScript cannot find the `window.exampleFunction` again.

Is this the behaviour you'd expect, or should user scripts be preserved when reloading a plugin? Also, am I even correct in thinking that you can reload a plugin into the same namespace as a prior existing one?

Thank you very much for your time. This library is very helpful indeed.

---

Here is my full source in case my explanation is insufficient.

## JS file: `userScript.js`

```
//  Copyright © 2017 shirakaba, www.github.com/shirakaba . All rights reserved.
"use strict"

exampleFunction(); // Invoke the JS function below immediately upon being added to the WebView.

function exampleFunction(){
  /* This will be called once Swift's Tokenising.romanise runs callback.call() on its XWVScriptObject. */
  function cb(originalsFromNative, transliterationsFromNative){
    var msg = 'Originals from Swift: ' + originalsFromNative + '; Transliterations from Swift: ' + transliterationsFromNative;
    webkit.messageHandlers.callbackHandler.postMessage(msg);

    var el = document.querySelectorAll('*');
    for(var i=0; i<el.length; i++) el[i].style.backgroundColor = 'green'; // Visually confirm that JS callback was called.
  }

  window.Tokenising.romaniseobj(cb, "Example text to tokenise"); // Run the Swift function.
}
```

## Swift file: `ViewController.js`

```
//  Copyright © 2017 shirakaba, www.github.com/shirakaba . All rights reserved.

import WebKit
import UIKit
import JavaScriptCore
import XWebView
import Foundation

class Tokenising: NSObject {
    dynamic var locale: CFLocale?
    
    @objc func romaniseobj(_ callback: XWVScriptObject, _ input: String) {
        callback.call(arguments: [["EXAMPLE", "TOKENS"], ["example", "transliterations"]], completionHandler: nil)
    }
    
    init(_ locale: String) { self.locale = NSLocale(localeIdentifier: locale); }
}

class ViewController: UIViewController, WKNavigationDelegate, UISearchBarDelegate, WKScriptMessageHandler {
    var webView: WKWebView!
    let jsvm: JSVirtualMachine = JSVirtualMachine()
    let injectlib = try! String(contentsOfFile: Bundle.main.path(forResource: "userScript", ofType: "js")!)
    
    override func loadView() {
        super.loadView()
        
        let userScript = WKUserScript(
            source: injectlib,
            injectionTime: WKUserScriptInjectionTime.atDocumentEnd,
            forMainFrameOnly: false
        )
        
        webView = WKWebView(frame: self.view.frame, configuration: WKWebViewConfiguration())
        webView.configuration.userContentController.addUserScript(userScript)
        webView.configuration.userContentController.add(self, name: "callbackHandler")
        webView.loadPlugin(Tokenising("zh-Hans"), namespace: "Tokenising")
        view = self.webView!
    }
    
    func userContentController(_ userContentController: WKUserContentController,didReceive message: WKScriptMessage) {
        if(message.name == "callbackHandler") { print("JavaScript is sending a message: \(message.body)"); }
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        /* Construct toolbar. */
        let reloadPlugin = UIBarButtonItem(barButtonSystemItem: .refresh, target: self, action: #selector(reloadThePlugin))
        let runExampleFunc = UIBarButtonItem(barButtonSystemItem: .action, target: self, action: #selector(runTheExampleFunc))
        toolbarItems = [reloadPlugin, runExampleFunc]
        navigationController?.isToolbarHidden = false
        
        let url = URL(string: "https://www.bbc.com/zhongwen/simp")!
        webView.load(URLRequest(url: url))
    }
    
    func reloadThePlugin(){
        webView.configuration.userContentController.removeAllUserScripts();
        webView.loadPlugin(Tokenising("ja"), namespace: "Tokenising");
    }
    
    func runTheExampleFunc(){
        webView.evaluateJavaScript("window.exampleFunction();", completionHandler: { result, error in
            print(result ?? "no 'result'."); print(error ?? "no 'error'.");
        })
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }

}
```

---

## Expected behaviour

**On startup:** app navigates to the [BBC's Chinese-language website](https://www.bbc.com/zhongwen/simp) and runs the user script, which calls `exampleFunction()` from a copy of the contents of `userScript.js`, thus setting the backgrounds of all elements on the webpage to green. Upon navigating to any new links, the background will continue to be set to green by this code being re-injected each time the document had loaded.

**On clicking the refresh button in the toolbar:** The plugin will be reloaded, this replacing the object in the "Tokenising" namespace with a new one that has been initialised in a different way.

**On clicking the action button in the toolbar:** `exampleFunction()` can be run manually before or after reloading the plugin, causing the webpage to turn green.

**On navigating to a new page after reloading the plugin:** the same behaviour described on startup should continue.

## Actual behaviour

**On startup:** Correct.

**On clicking the refresh button in the toolbar:** No error - probably works.

**On clicking the action button in the toolbar:** The `exampleFunction()` function can only be found by Javascript before reloading the plugin.

**On navigating to a new page after reloading the plugin:** The `exampleFunction` function can't be found, so it is not run and thus the page background doesn't become green.

**Comment by xwv** [comment]
Perhaps you need to unbind the plugin object before refresh.
```
// Don't use the loadPlugin helper method, create a channel and bind an object to it.
let channel = XWVChannel(webView: webView)
channel.bindPlugin(Tokenising("zh-Hans"), toNamespace: "Tokenizing")
......
......
// refresh
channel.unbind()
channel.bindPlugin(Tokenising("ja"), toNamespace: "Tokenizing")
```

I have never tried this before, and refreshing is not tested.

**Comment by shirakaba** [comment]
Thank you for the input. I've just tried that, and unfortunately it appears to have the same behaviour.

Note: if I try to refresh the plugin object more than once (via my original methodology, or via your bind/unbind methodology), this error is thrown:

```
Feb 21 20:35:16 org.xwebview.xwebview <E>:
Failed to inject script.
Error Domain=WKErrorDomain
Code=4 "A JavaScript exception occurred"
UserInfo={
    WKJavaScriptExceptionLineNumber=4,
    WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: XWVPlugin,
    WKJavaScriptExceptionSourceURL=http://www.bbc.com/zhongwen/simp/media/video,
    NSLocalizedDescription=A JavaScript exception occurred,
    WKJavaScriptExceptionColumnNumber=13
}
```

To be clear, this error isn't thrown after just the first refresh. I don't know whether this is of any help.

For now, I'll work around the problem instead; I don't know whether plugin refreshing was ever an intended use case. I think the functionality would provide some benefits, however, so I'm open to it appearing as a feature.

**EDIT:** Need to redo the test. Not sure whether `webView.configuration.userContentController.removeAllUserScripts();` was interfering.

**EDIT 2:** Redid the test without the aforementioned line; same behaviour as reported.

**Comment by shirakaba** [comment]
While we cannot reload plugins with a new object, I have learned that it is possible to dynamically update properties on plugins that have already been loaded into the webView, thus circumventing the need to reinitialise the plugin. If it is of help to anyone, here is how I am doing it:

```
//  Copyright © 2017 shirakaba, www.github.com/shirakaba . All rights reserved.

import WebKit
import UIKit
import JavaScriptCore
import XWebView
import Foundation

/** This class is a wrapper for any object, allowing it to be passed by reference.
  * This is useful for passing strings (which are passed by value if passed directly),
  * although is admittedly unnecessary for this example of passing CFLocale.
  * Forcing objects to be passed by reference, eg. by specifying the parameter as 'inout'
  * would be more elegant, but I couldn't get it working. */
class AnyByRef {
    var anyObj: Any!
    init(_ anyObj: Any) {  self.anyObj = anyObj; }
    func get() -> Any { return self.anyObj! as anyObj!; }
    func set(_ anyObj: Any) { self.anyObj = anyObj; }
}

/** The class that is loaded as a plugin into Javascript. */
class Tokenising: NSObject {
    dynamic var localeByRef: AnyByRef?
    
    @objc func romaniseobj(_ callback: XWVScriptObject, _ input: String) {
        var dynamicallyUpToDateLocale: NSLocale = localeByRef.get() as! NSLocale;
        // When JavaScript calls Tokenising.romaniseobj(), dynamicallyUpToDateLocale will be used here.
        callback.call(arguments: [["EXAMPLE", "TOKENS"], ["example", "transliterations"]], completionHandler: nil)
    }
    
    init(_ localeByRef: AnyByRef) { self.localeByRef = localeByRef; }
}

class ViewController: UIViewController, WKNavigationDelegate, UISearchBarDelegate, WKScriptMessageHandler {
    var webView: WKWebView!
    let jsvm: JSVirtualMachine = JSVirtualMachine()
    let injectlib = try! String(contentsOfFile: Bundle.main.path(forResource: "userScript", ofType: "js")!)
    var localeByRef: AnyByRef = AnyByRef(NSLocale(localeIdentifier: localeIdentifier)) // Initialise AnyByRef like so.

    override func loadView() {
        super.loadView()
        
        let userScript = WKUserScript(
            source: injectlib,
            injectionTime: WKUserScriptInjectionTime.atDocumentEnd,
            forMainFrameOnly: false
        )
        
        webView = WKWebView(frame: self.view.frame, configuration: WKWebViewConfiguration())
        webView.configuration.userContentController.addUserScript(userScript)
        webView.configuration.userContentController.add(self, name: "callbackHandler")
        webView.loadPlugin(Tokenising(localeByRef), namespace: "Tokenising")
        view = self.webView!
    }

    // See my first post for the rest of the (unrelated) code I used for this class.
}
```

As coding using this pattern is equally effective, I am closing this issue.
