### ISSUE TITLE
Pod version '0.12.0' seems not to work

### ISSUE THREAD

**Issue by igoMobile** [XWebView/XWebView#75]
Hi Guys,
I'm trying to integrate XWebView into my project with cocoapods:

`pod 'XWebView', '~> 0.12.0'`

But the version seems not to be available. I get this as response:

```
[!] Unable to satisfy the following requirements:

- `XWebView (~> 0.12.0)` required by `Podfile`
```

If I run 

`pod search XWebView`

from console, I get this:

```
-> XWebView (0.10.0)
   An extensible WebView (based on WKWebView) for iOS.
   pod 'XWebView', '~> 0.10.0'
   - Homepage: https://github.com/XWebView/XWebView
   - Source:   https://github.com/XWebView/XWebView.git
   - Versions: 0.10.0, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0 [master repo]
```

The version array finishes with 0.10.0...

**Comment by shirakaba** [comment]
Are you targeting an old version of Swift? The 0.10 version maps to Swift 2.3 and newer versions of XWebView map to Swift 3+.

Not that I'm an expert with Podfiles, but I set up my own Swift 3.0.2 project with XWebView 0.12.0 using that exact Podfile about three weeks ago, so I suspect that the podfile itself is at least correct.

**Comment by igoMobile** [comment]
Thanks for your quick reply! I use Swift 3.0.2 in my project. I'm also not an expert with pod files, but I suspect, this might be the issue. Here is the full error message when running pod install from console:

```
Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `XWebView (~> 0.12.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `XWebView (~> 0.12.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
```
It looks like the pod is not available anymore. That's why I tried to search for pod's available versions with this command: `pod search XWebView` The highest available version seems to be 0.10.0 and not 0.12.0  => - `Versions: 0.10.0, 0.9.5, 0.9.4, 0.9.3, 0.9.2, 0.9.1, 0.9.0 [master repo]`

**Comment by shirakaba** [comment]
I wonder why. Might be a question for @xwv . In the meantime, I can try sending you a zip of my 0.12.0 install so you can at least get developing until the problem is solved. I'll be able to do that in 2-3 hours from now, during my lunch break.

**Comment by shirakaba** [comment]
I just checked on [cocoapods.org](https://cocoapods.org/?q=xwebview) and it does seem to say that version 0.12.0 should be available. How about removing the '.0' from the end of the version number, as the webpage auto-generates the following Podfile config:

```
target 'MyApp' do
  pod 'XWebView', '~> 0.12'
end
```

Failing that, update cocoapods..? And failing that, I'll send you a zip of the current version later.

**Comment by igoMobile** [comment]
Thanks for your help. I updated my cocoapods from 1.1.0 to current version 1.2.0. Same error message.
I also tried out these variants:

```
pod 'XWebView', '~> 0.12'
pod 'XWebView', '0.12.0'
pod 'XWebView', '0.12'
```

Unfortunately, nothing helps. I'd try now to setup a new project and see wether it works in a fresh project. 
Yes, could you send me please the zip file with the latest sources? Great thanks in advance!

**Comment by igoMobile** [comment]
I found the cause and the fix for it! My Cocoapods setup was broken...s. [this](http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/).

And here is the fix. Just execute the commands below in your terminal

```
pod repo remove master
pod setup
pod install
```

**Comment by shirakaba** [comment]
Well done for tracking that down! Glad I didn't have to figure out how best to share that file. Please could you mark this issue as closed 👍

**Comment by igoMobile** [comment]
sure! thanks for your support!
