### ISSUE TITLE
xwebview iOS8.*

### ISSUE THREAD

**Issue by semnyqu** [XWebView/XWebView#83]
how to support ios 8.* in swift3.*

**Comment by xwv** [comment]
Sorry, the support of iOS 8.x was removed before migration of Swift 3.
You can check the old version of XWebView.swift file and bring it back for your apps.

**Comment by semnyqu** [comment]
Why?
so unreasonable!

**Comment by soflare** [comment]
The marketshare of iOS 8.x is very low now.
Please see the [official iOS version statistics](https://developer.apple.com/support/app-store/) and [an unofficial one](https://david-smith.org/iosversionstats/).
