### ISSUE TITLE
Swift 4 Issues

### ISSUE THREAD

**Issue by jkerrwilson** [XWebView/XWebView#85]
I've downloaded the iOS 11 preview which includes Swift 4 migration, and some build errors appear for the project.

I'll list any issues I find as I migrate my app to swift 4 here, as well as any solutions I find to any of this.

```swift
XWVMetaObject.swift:220:
Collection' requires the types 'XWVMetaObject.Element' (aka '(String, XWVMetaObject.Member)') and '(key: String, value: XWVMetaObject.Member)' be equivalent
XWVMetaObject.swift:220:1: 
Requirement specified as 'Self.Element' == 'Self.SubSequence.Element' [with Self = XWVMetaObject]
```
Compiler errors can be resolved for the above by adding:
```Swift
    typealias Element = (key: String, value: XWVMetaObject.Member)
    
    subscript(position: Dictionary<String, XWVMetaObject.Member>.Index) -> (key: String, value: XWVMetaObject.Member) {
        return members[position]
    }
```
To MetaObject. To be tested if this is actually correct in anyway. I have no idea what I'm doing.

The new SubString type causes issues in a few places which are not handled by the automatic Swift 4 converter:

```Swift
XWVHttpConnection:254
var value = String(line[line.index(after: colon) ..< line.endIndex])
```
Required copy back to a string before trim operations can be performed

There are a few different instances of:
> Comparing non-optional value of type 'objc_property_t' (aka 'OpaquePointer') to nil always returns true

All of which are in a similar form to
```Swift
while variable != nil {
    ...
}
```
I'm not sure what to do with these as they look to be enumerations, maybe the end condition has changed in Swift 4.

Finally, for now,
> The use of Swift 3 @objc inference in Swift 4 mode is deprecated. Please address deprecated @objc inference warnings, test your code with “Use of deprecated Swift 3 @objc inference” logging enabled, and disable Swift 3 @objc inference.

Just a deprecation though.

**Comment by jkerrwilson** [comment]
More stuff with the tests. It seems implicit objc entry points are deprecated and throw in Swift 4. Not a huge deal, @objc just needs to be added in a lot of places to make the objc entry point explicit.

**Comment by xwv** [comment]
Thanks a lot. Go on please, I'm looking forward your PR 😃 
Currently, I have no time and hardware to do this work. Sorry for that.
Any question about the source code, please raise here, and I will help you.
BTW, I suggest that you should try to migrate to 3.2 firstly.

**Comment by jkerrwilson** [comment]
I have a compiling version, that seems to run okay inside my app, but not all tests are passing at the moment. How to fix the remaining issues might be beyond my iOS experience.

I'm happy to put what I've done so far on a branch for others to look at, work on, and use. I do not know how much more time I will be able to put into this.

**Comment by xwv** [comment]
Thanks for the helpful PR.
