### ISSUE TITLE
Something is wrong in xcode9.1

### ISSUE THREAD

**Issue by limxing** [XWebView/XWebView#94]
../Pods/XWebView/XWebView/XWVBindingObject.swift:53:22: 'performSelector' produces 'Void', not the expected contextual result type 'AnyObject!'

../Pods/XWebView/XWebView/XWVBindingObject.swift:87:44: Missing argument label 'inBackground:' in call
......
81 issues

Anyone who encounter it and how to solve? Thank you

**Comment by xwv** [comment]
Could you please try to build the code fetched from GitHub instead of CocoaPods.
CocoaPods release is outdated.

**Comment by semnyqu** [comment]
why not update the CocoaPods release ?@xwv

**Comment by xwv** [comment]
@semnyqu , I have very limited time to maintain the project, and I'm not even using it now. If you or someone else want to help, I can delegate the Cocoapods maintenance to you or him/her.

**Comment by limxing** [comment]
为啥没时间@xwv

**Comment by xwv** [comment]
@limxing I have work to do, especially very busy recent months. And also I have family to take care. I only spend spare time on this project. The Cocoapods maintenance is somewhat boring, I'd rather spend time on new features. There are some commits in [my development repo](https://github.com/xwv/XWebView/commits/master) are waiting to push.

BTW, It seems many users are from China. I'd like to create a WeChat group to improve communication with those developers, to hear your questions, requirements, criticism and encouragement, to learn from you and also to help each other. So if anyone want to join, add me (id: xwebview) to your WeChat.
